### ISSUE TITLE
Can Not Activate

### ISSUE THREAD

**Issue by Tunetrax** [NialtoServices/Extractor-IO#2]
I have installed the Extractor plugin but I can not Activate the Plugin?

![extractor](https://cloud.githubusercontent.com/assets/12283069/7505002/67e18364-f403-11e4-8844-3bd993a88b73.jpg)

**Comment by indotronic** [comment]
Same problem with me, but solved now.. :)

**Comment by Tunetrax** [comment]
How did you solve it?

**Comment by indotronic** [comment]
open extractorio.php with editor

go to line : 114 (if use editor wordpress just find this script with ctr+f)
delete '[0]" in $data = ImportIO::instance()->query_url( $_POST['url'], $connector )[0]; 
so $data = ImportIO::instance()->query_url( $_POST['url'], $connector );

go to line 520 
delete "[$connector_id]" in $connector = get_option( 'ns_extractor_connectors' )[$connector_id];
so $connector = get_option( 'ns_extractor_connectors' );

save,
and activate

**Comment by indotronic** [comment]
but, after activating this plugin, i dont know how to use it.. :(

**Comment by Tunetrax** [comment]
Thank you.. I appear to have a working Plugin now. I am currently working on getting the API key from import.io I will let you know if I get this working once I have the API key

**Comment by tobyaherbert** [comment]
Hi Guys, this plugin is a little buggy at the moment.
I'm working on a new version that should have all the fixes in it.
I'll post an update when the new version is available.

**Comment by tobyaherbert** [comment]
I've released a new version of the plugin rewritten from the ground up.
See if that works :)
