### ISSUE TITLE
Can not Activate

### ISSUE THREAD

**Issue by Tunetrax** [NialtoServices/Extractor-IO#3]
Just like the previous version, after installing the Plugin I can not activate it from the Plugins page

**Comment by tobyaherbert** [comment]
Does WordPress give you any indication of why it couldn't activate the plugin?

**Comment by Tunetrax** [comment]
Just tried again and got this message:

Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected T_FUNCTION in /home/content/63/10226863/html/wp-content/plugins/Extractor-IO-master/includes/class-eio-menu-manager.php on line 119

**Comment by tobyaherbert** [comment]
Hmm. Do you know what version of PHP your site is using?

**Comment by Tunetrax** [comment]
We are hosted at Godaddy. I just looked and we are at 5.2 with the options of going to the current 5.3 or the newest 5.4 with this message "PHP 5.3 is our default version. PHP version 5.4 is available and meets our stability and security requirements. Version 5.2 isn’t actively supported."

**Comment by tobyaherbert** [comment]
Ah, thats the issue. The plugin requires PHP at minimum PHP 5.3 as it uses Closures (which were introduces in 5.3). If you switch to at least 5.3 it should work.

**Comment by Tunetrax** [comment]
I just got this message fro Godaddy "Upgrading to PHP 5.3 might cause compatibility issues with code on your site. Installed applications might not run under this new version." Do you know if this should cause problems with Wordpress 4.2.2

**Comment by tobyaherbert** [comment]
We run all our WordPress installations on PHP 5.4 without any issues so it should be fine.

**Comment by Tunetrax** [comment]
Ok. finally Godaddy switched me to 5.4 and The module activated. I will let you know when i get the Plugin working with import.io  Thanks
