### ISSUE TITLE
Import.io

### ISSUE THREAD

**Issue by Tunetrax** [NialtoServices/Extractor-IO#4]
Have you successfully created an import.io connector and used it on a worpress site? I am trying to create a page that shows all our latest videos on youtube. I have created both a Magic API and and an Extractor but I get the "No Connectors Found" message when I go to your plugin Extract and I get the "Not connected to Import IO" when i go to Settings?

**Comment by tobyaherbert** [comment]
Ok, did you put your User ID and API Key in the settings panel?

Also this plugin only works with the Extractor type connectors.

**Comment by Tunetrax** [comment]
Yes I used the User ID and API key from my import.io  Account

**Comment by tobyaherbert** [comment]
Hmmm. The 'Not connected to Import IO' means that is can't connect to your account.

Are the User ID and API Key correctly formatted?

They should be in the following format:

User ID: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa (where a is either a letter or number)
API Key: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb (where a matches the User ID and b is a letter, number or symbol)

**Comment by Tunetrax** [comment]
Ok ... imporrt.io copy was putting in some extra space. I have connection now. Now I can not get the Extraction URL right?

**Comment by tobyaherbert** [comment]
Ok great. I'll push an update that strips whitespace from the User ID and API Key automatically just encase someone else has the same issue :)

What's wrong with your extraction URL? Does the plugin throw an error when you try to extract using it?

**Comment by Tunetrax** [comment]
I am not exactly sure what you want here from import.io 
![importio1](https://cloud.githubusercontent.com/assets/12283069/7556509/74514eea-f728-11e4-9235-642d2c98c795.jpg)

**Comment by tobyaherbert** [comment]
Ok so in the Extractor IO plugin, go to 'Extract' in the sidebar, then enter the Extraction URL: https://www.youtube.com/user/drhurd52/videos and choose 'StudioOn4th Youtube' as the connector

**Comment by tobyaherbert** [comment]
Did you configure the Connector Mapping yet though?

**Comment by Tunetrax** [comment]
I set them both to Post Content.
![importio2](https://cloud.githubusercontent.com/assets/12283069/7556530/73df5320-f729-11e4-96ac-81e4e3897f67.jpg)

**Comment by tobyaherbert** [comment]
That's fine. It will automatically download the images from the source site, add them to your site's media and then attach it to the post automatically.

**Comment by Tunetrax** [comment]
Ok, now i get this but only one of the Youtube videos is showing up on the Post?
![importio3](https://cloud.githubusercontent.com/assets/12283069/7556541/f6521810-f729-11e4-9df8-271e8d3911ca.jpg)

**Comment by Tunetrax** [comment]
What I am trying to do is to replace the RSS feed I used to be able to use to populate our Archived Videos page on our site at http://studioon4th.com/archived-videos-3/
Youtube's RSS feed does not work anymore as of yesterday

**Comment by tobyaherbert** [comment]
Ok, that's a strange issue. I'm writing an update to the plugin that should allow me to see why it isn't pulling those other images in. I'll let you know when the update is available.

Sorry for all the issues.

**Comment by tobyaherbert** [comment]
Hi Tunetrax,

I've released an update to the plugin which you'll need to download and install.
As it's a zip file, you will have to delete the current version on your WordPress site, then upload the new version.

Once you have installed and setup the new version, there will be a 'Generate Report' option in the extractor.

If you email the report to support@nialtoservices.co.uk, I can take a look for you.

**Comment by tobyaherbert** [comment]
Hi Tunetrax,

Thanks for the update. I never received the original email though I can see the file attached.

I'm looking into this now for you.

Again sorry for the delay :(

**Comment by tobyaherbert** [comment]
Hi Tunetrax,

I believe i've fixed the issue. Could you install the new version of the plugin, then try extracting data again?

Thanks

P.S. Also you might want to check that the plugin didn't accidentally create a load of posts due to this bug.

**Comment by Tunetrax** [comment]
I installed the new update and ran the extraction. The resulting Post still only had one image and text from the Extractor which has 30 Images with Text

**Comment by tobyaherbert** [comment]
Hi Tunetrax,

I'm still looking into this for you. I'll post an update when i've fixed the issue.

**Comment by tobyaherbert** [comment]
Hi Tunetrax,

Sorry for the delay, I've been caught up working on a project.

I believe the issue has been resolved. Once again you'll have to delete and reinstall the plugin (it should work this time though :)).

**Comment by freetemplateslife** [comment]
Hi,

When i add my api key, it says i'm connected, but then at Extract it says No Connectors Found.
Can you help?

**Comment by jamesscaggs** [comment]
I have a unique/complex implementation I need to complete. I do not need to "create" posts from my data but rather insert some data into existing custom post types.
1. I have an Import.io data set (a Magic API that refreshes automatically daily) - http://screencast.com/t/e8nncCJeYp
2. I have a "tours/activities" custom post type in my Wordpress theme where I would like to display reviews from my data set.
3. I would like this to have ability to refresh this data with a button click.

Is this a customization you would be interested in taking on as a project?

**Comment by Tunetrax** [comment]
Sorry, I have a full work load right now and probably for the next two months at least.
Doug Hurd

Date: Sun, 1 Nov 2015 16:02:41 -0800
