### ISSUE TITLE
Internal server eror

### ISSUE THREAD

**Issue by LiveRock** [NialtoServices/Extractor-IO#6]
I followed all the steps but when I clicked on EXTRACT DATA inside WordPress, I get an Internal Server error. When i managed to log in again, I noticed that there is a new post but there are no content inside.

May I know what did I do wrong here?
Thanks!

**Comment by tobyaherbert** [comment]
Hey LiveRock,

Not sure what's wrong there, could be that a required PHP extension (like cURL) is missing.

You could try enabling debug mode on your WP site or checking your site's error log to see if there is any more info on what went wrong.

Hope that helps.

**Comment by LiveRock** [comment]
Hi Toby
I tried another website and it worked. I guess not all website can be extracted easily.
Thank you very much for responding promptly. All the best!
